"""состояние игры в БД: точки раундов, челленджи, таймер, пул панорам

Revision ID: 03dd9afa99a2
Revises: 5f7875fb0c81
Create Date: 2026-07-06 14:52:37.233080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03dd9afa99a2'
down_revision = '5f7875fb0c81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('lat_key', sa.Integer(), nullable=False),
    sa.Column('lon_key', sa.Integer(), nullable=False),
    sa.Column('dist_from_center_km', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lat_key', 'lon_key', name='uq_verified_points_key')
    )
    with op.batch_alter_table('game_rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gen_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gen_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('skips', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('answered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('timed_out', sa.Boolean(), nullable=True))

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_round', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('challenge_token', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('challenged_from_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_sessions_challenge_token'), ['challenge_token'], unique=True)
        batch_op.create_foreign_key('fk_game_sessions_challenged_from', 'game_sessions', ['challenged_from_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_game_sessions_challenged_from', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_game_sessions_challenge_token'))
        batch_op.drop_column('challenged_from_id')
        batch_op.drop_column('challenge_token')
        batch_op.drop_column('time_limit')
        batch_op.drop_column('current_round')

    with op.batch_alter_table('game_rounds', schema=None) as batch_op:
        batch_op.drop_column('timed_out')
        batch_op.drop_column('answered_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('skips')
        batch_op.drop_column('address')
        batch_op.drop_column('gen_longitude')
        batch_op.drop_column('gen_latitude')

    op.drop_table('verified_points')
    # ### end Alembic commands ###
