"""удаление легаси: таблица locations и game_rounds.location_id

Revision ID: 3d43cf32f2f6
Revises: 03dd9afa99a2
Create Date: 2026-07-07 01:09:54.937629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d43cf32f2f6'
down_revision = '03dd9afa99a2'
branch_labels = None
depends_on = None


def upgrade():
    # SQLite: batch-перестройка game_rounds без колонки удаляет и её FK —
    # отдельный drop_constraint невозможен (констрейнт безымянный) и не нужен.
    # Колонку удаляем раньше самой таблицы locations, чтобы при перестройке
    # не осталось ссылки на несуществующую таблицу.
    with op.batch_alter_table('game_rounds', schema=None) as batch_op:
        batch_op.drop_column('location_id')

    op.drop_table('locations')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=False),
    sa.Column('longitude', sa.FLOAT(), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('difficulty', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # Колонку возвращаем без FK: безымянный констрейнт в batch-режиме SQLite
    # не пересоздать; для отката достаточно самой колонки.
    with op.batch_alter_table('game_rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
