"""режим без перемещения (no_move)

Revision ID: 736ef40ee59e
Revises: ebfd52ca2fad
Create Date: 2026-07-07 18:16:50.696125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '736ef40ee59e'
down_revision = 'ebfd52ca2fad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_move', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_column('no_move')

    # ### end Alembic commands ###
