"""ежедневный вызов, самоочистка пула, дата daily-игры

Revision ID: ebfd52ca2fad
Revises: 3d43cf32f2f6
Create Date: 2026-07-07 12:36:41.831325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebfd52ca2fad'
down_revision = '3d43cf32f2f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('points_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_challenges_date'), ['date'], unique=True)

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_date', sa.Date(), nullable=True))
        batch_op.create_index(batch_op.f('ix_game_sessions_daily_date'), ['daily_date'], unique=False)

    with op.batch_alter_table('verified_points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fail_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verified_points', schema=None) as batch_op:
        batch_op.drop_column('fail_count')

    with op.batch_alter_table('game_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_sessions_daily_date'))
        batch_op.drop_column('daily_date')

    with op.batch_alter_table('daily_challenges', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_challenges_date'))

    op.drop_table('daily_challenges')
    # ### end Alembic commands ###
